apiVersion: batch/v1
kind: Job
metadata:
  name: init-minio
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: init-minio
          image: quay.io/gthomas59800/kto/init-minio-2023-2024
          env:
            - name: MINIO_ENDPOINT
              value: "http://minio-api-{%user%}-dev.apps.sandbox-{%cluster%}.openshiftapps.com"
          resources:
            limits:
              cpu: 1300m
              memory: 4000Mi
            requests:
              cpu: 1300m
              memory: 4000Mi
      restartPolicy: Never
